version: 1
disable_existing_loggers: no
formatters:
  default:
    format: "%(asctime)s [%(threadName)s] %(levelname)s %(name)s - [%(module)s,%(funcName)s,%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    when: D
    interval: 1
    backupCount: 7
    filename: ./logs/translator.log
loggers:
  root:
    level: INFO
    handlers: [console, file]